package alice;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.Objects;

import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.shape.Circle;

/**
 * Controls the FXML chat screen and connects it to Alice's command engine.
 */
public class MainController {
    @FXML
    private ImageView headerAvatar;
    @FXML
    private ScrollPane conversationScroll;
    @FXML
    private VBox messageContainer;
    @FXML
    private TextField commandField;
    @FXML
    private Button sendButton;

    private final ByteArrayOutputStream responseBuffer = new ByteArrayOutputStream();
    private final PrintStream responseStream = new PrintStream(responseBuffer, true, StandardCharsets.UTF_8);
    private Image aliceAvatar;
    private Ui chatUi;
    private Alice alice;

    /**
     * Initializes the avatar, command engine, and opening greeting.
     */
    @FXML
    private void initialize() {
        aliceAvatar = new Image(Objects.requireNonNull(
                MainController.class.getResourceAsStream("/images/alice-avatar.png")));
        headerAvatar.setImage(aliceAvatar);
        headerAvatar.setSmooth(false);
        headerAvatar.setClip(new Circle(29, 29, 29));

        chatUi = new Ui(responseStream);
        alice = new Alice(Main.getDefaultFilePath(), chatUi);
        messageContainer.heightProperty().addListener((observable, oldHeight, newHeight) -> scrollToBottom());
        responseBuffer.reset();
        chatUi.printChatGreetings();
        appendAliceMessage(responseBuffer.toString(StandardCharsets.UTF_8).trim());
        responseBuffer.reset();
    }

    /**
     * Sends the command currently entered by the user.
     */
    @FXML
    private void handleSend() {
        String command = commandField.getText();
        if (command == null || command.isBlank()) {
            return;
        }

        appendUserMessage(command);
        responseBuffer.reset();
        boolean keepRunning = alice.processCommand(command);
        String response = responseBuffer.toString(StandardCharsets.UTF_8).trim();
        if (!response.isEmpty()) {
            appendAliceMessage(response);
        }

        commandField.clear();
        if (!keepRunning) {
            commandField.setDisable(true);
            sendButton.setDisable(true);
        }
    }

    /**
     * Adds a right-aligned user message to the conversation.
     *
     * @param text The command entered by the user.
     */
    private void appendUserMessage(String text) {
        Label avatar = createAvatar("E", "user-avatar");
        Label bubble = createBubble(text, "user-bubble");
        HBox row = new HBox(10, bubble, avatar);
        row.setAlignment(Pos.BOTTOM_RIGHT);
        row.getStyleClass().add("message-row");
        messageContainer.getChildren().add(row);
        scrollToBottom();
    }

    /**
     * Adds a left-aligned Alice message to the conversation.
     *
     * @param text The response generated by Alice.
     */
    private void appendAliceMessage(String text) {
        ImageView avatar = new ImageView(aliceAvatar);
        avatar.setFitWidth(42);
        avatar.setFitHeight(42);
        avatar.setSmooth(false);
        avatar.setClip(new Circle(21, 21, 21));
        Label bubble = createBubble(text, "alice-bubble");
        HBox row = new HBox(10, avatar, bubble);
        row.setAlignment(Pos.BOTTOM_LEFT);
        row.getStyleClass().add("message-row");
        messageContainer.getChildren().add(row);
        scrollToBottom();
    }

    /**
     * Creates a styled message bubble.
     *
     * @param text The text to display.
     * @param styleClass The CSS style class for the bubble.
     * @return The configured message label.
     */
    private Label createBubble(String text, String styleClass) {
        Label bubble = new Label(text);
        bubble.setWrapText(true);
        bubble.setMaxWidth(650);
        bubble.getStyleClass().addAll("message-bubble", styleClass);
        return bubble;
    }

    /**
     * Creates a circular initial avatar.
     *
     * @param initial The letter displayed in the avatar.
     * @param styleClass The CSS style class for the avatar.
     * @return The configured avatar label.
     */
    private Label createAvatar(String initial, String styleClass) {
        Label avatar = new Label(initial);
        avatar.getStyleClass().addAll("avatar", styleClass);
        return avatar;
    }

    /**
     * Scrolls the conversation to the latest message after layout updates.
     */
    private void scrollToBottom() {
        Platform.runLater(() -> conversationScroll.setVvalue(1.0));
    }
}
